# Generated by Django 3.1.3 on 2020-11-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20201117_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='categories_set',
            field=models.ManyToManyField(blank=True, to='ads.Ad'),
        ),
    ]
