# Generated by Django 3.1.3 on 2020-11-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20201119_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories_set',
            new_name='category_set',
        ),
    ]
