# Generated by Django 3.1.4 on 2020-12-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20201119_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_set',
        ),
        migrations.AddField(
            model_name='ad',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='ads.Category'),
        ),
    ]
