# Generated by Django 3.1.4 on 2020-12-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20201212_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category', to='ads.Category'),
        ),
    ]
